### 问题
``` js
o = Object.create({say(){console.log(this.name)}}, {
    name: {
        value: 'google'
    }
});
o.say(); // google

for (const name in o) console.log(name); // 猜猜看？
```
- 不错的缓存文章
http://www.cnblogs.com/vajoy/p/5341664.html

``` bash
cache-control：
// no-cache 意味着要上服务器确认，304就304
// no-store 直接请求。
```

- 判断promise对象
``` js
p =  Reflect.construct(Promise, [(r, j) => {}]); // 'object'
/Promise/.test(p + '') === true; //

if (typeof p === ('object' || typeof p === 'function') && p.then === 'function') {}
```

- 字符串去重 // 2333，只要有序就部署@@iterator？
``` js
Array.from(new Set('aabbcc')).join('');
```

- 错误码
``` js
414 Request_URI Too Long uri太长
413 Request Entity Too Large 请求头太大
```

1. 先抓包看看：
``` bash
tcpdump -D # 查看适配器
tcpdump -i en0 # 选择网卡 也可以 tcpdump --interface en0 / tcpdump --interface=en0
tcpdump -i en5 host jsplayer.cn and port 80 # 监听指定host的域名，流水号不对需要加 --absolute-tcp-sequence-numbers
```
看看结果：

GET请求：
``` bash
14:28:53.975107 IP 172.24.133.54.57042 > 39.108.161.155.http: Flags [S], seq 3641634636
14:28:54.016946 IP 39.108.161.155.http > 172.24.133.54.57042: Flags [S.], seq 3325668570, ack 3641634637
14:28:54.017003 IP 172.24.133.54.57042 > 39.108.161.155.http: Flags [.], ack 3325668571

14:28:54.017181 IP 172.24.133.54.57042 > 39.108.161.155.http: Flags [P.], seq 3641634637:3641635080, ack 3325668571, length 443: HTTP: GET /ip.txt HTTP/1.1
14:28:54.058358 IP 39.108.161.155.http > 172.24.133.54.57042: Flags [.], ack 3641635080
14:28:54.058374 IP 39.108.161.155.http > 172.24.133.54.57042: Flags [FP.], seq 3325668571:3325669044, ack 3641635080, length 473: HTTP: HTTP/1.1 200 OK

14:28:54.058427 IP 172.24.133.54.57042 > 39.108.161.155.http: Flags [.], ack 3325669045, win 4089, options [nop,nop,TS val 770544994 ecr 1834651813], length 0
14:28:54.059004 IP 172.24.133.54.57042 > 39.108.161.155.http: Flags [F.], seq 3641635080, ack 3325669045, win 4096, options [nop,nop,TS val 770544994 ecr 1834651813], length 0
14:28:54.111108 IP 39.108.161.155.http > 172.24.133.54.57042: Flags [.], ack 3641635081, win 235, options [nop,nop,TS val 1834651823 ecr 770544994], length 0
```

POST请求：
``` bash
15:05:04.294423 IP 172.24.133.54.50465 > 39.108.161.155.http: Flags [S], seq 1505462790, length 0
15:05:04.336568 IP 39.108.161.155.http > 172.24.133.54.50465: Flags [S.], seq 2080762434, ack 1505462791, length 0
15:05:04.336745 IP 172.24.133.54.50465 > 39.108.161.155.http: Flags [.], ack 2080762435, length 0
15:05:04.337506 IP 172.24.133.54.50465 > 39.108.161.155.http: Flags [P.], seq 1505462791:1505463202, ack 2080762435, length 411: HTTP: POST /data/timeout HTTP/1.1
15:05:04.378766 IP 39.108.161.155.http > 172.24.133.54.50465: Flags [.], ack 1505463202, length 0
15:05:04.396956 IP 39.108.161.155.http > 172.24.133.54.50465: Flags [P.], seq 2080762435:2080762784, ack 1505463202, length 349: HTTP: HTTP/1.1 200 OK

15:05:04.396987 IP 39.108.161.155.http > 172.24.133.54.50465: Flags [F.], seq 2080762784, ack 1505463202
15:05:04.397097 IP 172.24.133.54.50465 > 39.108.161.155.http: Flags [.], ack 2080762784, length 0
15:05:04.397199 IP 172.24.133.54.50465 > 39.108.161.155.http: Flags [.], ack 2080762785, length 0
15:05:04.397965 IP 172.24.133.54.50465 > 39.108.161.155.http: Flags [F.], seq 1505463202, ack 2080762785, length 0
15:05:04.437082 IP 39.108.161.155.http > 172.24.133.54.50465: Flags [.], ack 1505463203, length 0
```

#### 一些总结和提问：

1. response empty 是MSL引起的么？
2. ngx设置TCP keepAlive 和 http的keep-alive 有啥区别，为啥说他俩不是一个东西
3. ngx 如何设置post请求，是75秒吗？ // 是，通过 keepalive_timeout 60s 设置超过75s，1min就结束了（是浏览器行为么），超时status 504 ，报文摘要： Gateway Time-out；
既然是浏览器行为，那么轮询设置大一些有问题么。
4. 按照最后一个ack 等待2MSL，那么keep-alive到底多久？ // 我理解就是2 * 2min（window 2 * 4min）,tcp keepAlive 和 http header 不是一回事
5. Flags are some combination  of  S  (SYN),  F(FIN), P (PUSH), R (RST), U (URG), W (ECN CWR), E (ECN-Echo) or `.' (ACK), or `none' if no flags are set.  (^-^)
6. 为啥最后一次握手不需要SYN？
7. 可以看到[.] 是ACK那么，http后面的ack要干嘛。。似乎与nagle算法有关
8. post 发两个包这个。。不存在的。有人测过ruby分很多包，而且每个包都没超过TCP数据帧大小。
    - 以太网数据帧大小： 1518Byte，头部信息14Byte，尾部checksum 14Byte，所以留给上层协议的数据大小是 1518 - 14 - 4 = 1500
    - 1518 是从哪来的呢？
    假设MTU和IP数据包大小一样，都是 65535（64k），因为光信号一次只能发一个以太网帧（14 + 4 + 65535 = 65553），那么如果网速是2m的，需要
    64k / (2mbps / 8 * 1024) = .25s,也就是传一帧要 250ms， 游戏一帧 16.7ms。那如果小点呢。
    - UDP 包的大小就应该是 1500 - IP头(20) - UDP头(8) = 1472(Bytes) - 脑补（1Byte = 8bit,0xFF === 255 === 0b11111111）
    - TCP 包的大小就应该是 1500 - IP头(20) - TCP头(20) = 1460 (Bytes) // 抓包显示： 1368
9. Maximum Transmission Unit(MTU) 最大传输单元，是数据链路层的payload，也就是上层协议的大小，例如IP，ICMP等
10. URL constructor 兼容性： ie11+
``` js
const {searchParams: u} = new URL(location.href);
u.get('abc'); // def
u.entries()// [[k, v]];
```
11. 作用域问题
``` js
a = {
	sayName() {
		console.log(sayName, this);
	}
};
a.sayName(); // 肯定不行啦


{
	const sayName = function() {
		console.log(sayName, this);
	}
	sayName(); // 这样是没问题的，作用域问题
};
```

- Promise
``` js
/**
 * Promise 实现 遵循promise/A+规范
 * Promise/A+规范译文:
 * https://malcolmyu.github.io/2015/06/12/Promises-A-Plus/#note-4
 */

// promise 三个状态
const PENDING = "pending";
const FULFILLED = "fulfilled";
const REJECTED = "rejected";

function Promise(excutor) {
    let self = this; // 缓存当前promise实例对象
    self.status = PENDING; // 初始状态
    self.value = undefined; // fulfilled状态时 返回的信息
    self.reason = undefined; // rejected状态时 拒绝的原因
    self.onFulfilledCallbacks = []; // 存储fulfilled状态对应的onFulfilled函数
    self.onRejectedCallbacks = []; // 存储rejected状态对应的onRejected函数

    function resolve(value) { // value成功态时接收的终值
        if(value instanceof Promise) {
            return value.then(resolve, reject);
        }

        // 为什么resolve 加setTimeout?
        // 2.2.4规范 onFulfilled 和 onRejected 只允许在 execution context 栈仅包含平台代码时运行.
        // 注1 这里的平台代码指的是引擎、环境以及 promise 的实施代码。实践中要确保 onFulfilled 和 onRejected 方法异步执行，且应该在 then 方法被调用的那一轮事件循环之后的新执行栈中执行。

        setTimeout(() => {
            // 调用resolve 回调对应onFulfilled函数
            if (self.status === PENDING) {
                // 只能由pending状态 => fulfilled状态 (避免调用多次resolve reject)
                self.status = FULFILLED;
                self.value = value;
                self.onFulfilledCallbacks.forEach(cb => cb(self.value));
            }
        });
    }

    function reject(reason) { // reason失败态时接收的拒因
        setTimeout(() => {
            // 调用reject 回调对应onRejected函数
            if (self.status === PENDING) {
                // 只能由pending状态 => rejected状态 (避免调用多次resolve reject)
                self.status = REJECTED;
                self.reason = reason;
                self.onRejectedCallbacks.forEach(cb => cb(self.reason));
            }
        });
    }

    // 捕获在excutor执行器中抛出的异常
    // new Promise((resolve, reject) => {
    //     throw new Error('error in excutor')
    // })
    try {
        excutor(resolve, reject);
    } catch (e) {
        reject(e);
    }
}

/**
 * resolve中的值几种情况：
 * 1.普通值
 * 2.promise对象
 * 3.thenable对象/函数
 */

/**
 * 对resolve 进行改造增强 针对resolve中不同值情况 进行处理
 * @param  {promise} promise2 promise1.then方法返回的新的promise对象
 * @param  {[type]} x         promise1中onFulfilled的返回值
 * @param  {[type]} resolve   promise2的resolve方法
 * @param  {[type]} reject    promise2的reject方法
 */
function resolvePromise(promise2, x, resolve, reject) {
    if (promise2 === x) {  // 如果从onFulfilled中返回的x 就是promise2 就会导致循环引用报错
        return reject(new TypeError('循环引用'));
    }

    let called = false; // 避免多次调用
    // 如果x是一个promise对象 （该判断和下面 判断是不是thenable对象重复 所以可有可无）
    if (x instanceof Promise) { // 获得它的终值 继续resolve
        if (x.status === PENDING) { // 如果为等待态需等待直至 x 被执行或拒绝 并解析y值
            x.then(y => {
                resolvePromise(promise2, y, resolve, reject);
            }, reason => {
                reject(reason);
            });
        } else { // 如果 x 已经处于执行态/拒绝态(值已经被解析为普通值)，用相同的值执行传递下去 promise
            x.then(resolve, reject);
        }
        // 如果 x 为对象或者函数
    } else if (x != null && ((typeof x === 'object') || (typeof x === 'function'))) {
        try { // 是否是thenable对象（具有then方法的对象/函数）
            let then = x.then;
            if (typeof then === 'function') {
                then.call(x, y => {
                    if(called) return;
                    called = true;
                    resolvePromise(promise2, y, resolve, reject);
                }, reason => {
                    if(called) return;
                    called = true;
                    reject(reason);
                })
            } else { // 说明是一个普通对象/函数
                resolve(x);
            }
        } catch(e) {
            if(called) return;
            called = true;
            reject(e);
        }
    } else {
        resolve(x);
    }
}

/**
 * [注册fulfilled状态/rejected状态对应的回调函数]
 * @param  {function} onFulfilled fulfilled状态时 执行的函数
 * @param  {function} onRejected  rejected状态时 执行的函数
 * @return {function} newPromsie  返回一个新的promise对象
 */
Promise.prototype.then = function(onFulfilled, onRejected) {
    const self = this;
    let newPromise;
    // 处理参数默认值 保证参数后续能够继续执行
    onFulfilled =
        typeof onFulfilled === "function" ? onFulfilled : value => value;
    onRejected =
        typeof onRejected === "function" ? onRejected : reason => {
            throw reason;
        };

    // then里面的FULFILLED/REJECTED状态时 为什么要加setTimeout ?
    // 原因:
    // 其一 2.2.4规范 要确保 onFulfilled 和 onRejected 方法异步执行(且应该在 then 方法被调用的那一轮事件循环之后的新执行栈中执行) 所以要在resolve里加上setTimeout
    // 其二 2.2.6规范 对于一个promise，它的then方法可以调用多次.（当在其他程序中多次调用同一个promise的then时 由于之前状态已经为FULFILLED/REJECTED状态，则会走的下面逻辑),所以要确保为FULFILLED/REJECTED状态后 也要异步执行onFulfilled/onRejected

    // 其二 2.2.6规范 也是resolve函数里加setTimeout的原因
    // 总之都是 让then方法异步执行 也就是确保onFulfilled/onRejected异步执行

    // 如下面这种情景 多次调用p1.then
    // p1.then((value) => { // 此时p1.status 由pending状态 => fulfilled状态
    //     console.log(value); // resolve
    //     // console.log(p1.status); // fulfilled
    //     p1.then(value => { // 再次p1.then 这时已经为fulfilled状态 走的是fulfilled状态判断里的逻辑 所以我们也要确保判断里面onFulfilled异步执行
    //         console.log(value); // 'resolve'
    //     });
    //     console.log('当前执行栈中同步代码');
    // })
    // console.log('全局执行栈中同步代码');
    //

    if (self.status === FULFILLED) { // 成功态
        return newPromise = new Promise((resolve, reject) => {
            setTimeout(() => {
                try{
                    let x = onFulfilled(self.value);
                    resolvePromise(newPromise, x, resolve, reject); // 新的promise resolve 上一个onFulfilled的返回值
                } catch(e) {
                    reject(e); // 捕获前面onFulfilled中抛出的异常 then(onFulfilled, onRejected);
                }
            });
        })
    }

    if (self.status === REJECTED) { // 失败态
        return newPromise = new Promise((resolve, reject) => {
            setTimeout(() => {
                try {
                    let x = onRejected(self.reason);
                    resolvePromise(newPromise, x, resolve, reject);
                } catch(e) {
                    reject(e);
                }
            });
        });
    }

    if (self.status === PENDING) { // 等待态
        // 当异步调用resolve/rejected时 将onFulfilled/onRejected收集暂存到集合中
        return newPromise = new Promise((resolve, reject) => {
            self.onFulfilledCallbacks.push((value) => {
                try {
                    let x = onFulfilled(value);
                    resolvePromise(newPromise, x, resolve, reject);
                } catch(e) {
                    reject(e);
                }
            });
            self.onRejectedCallbacks.push((reason) => {
                try {
                    let x = onRejected(reason);
                    resolvePromise(newPromise, x, resolve, reject);
                } catch(e) {
                    reject(e);
                }
            });
        });
    }
};

/**
 * Promise.all Promise进行并行处理
 * 参数: promise对象组成的数组作为参数
 * 返回值: 返回一个Promise实例
 * 当这个数组里的所有promise对象全部变为resolve状态的时候，才会resolve。
 */
Promise.all = function(promises) {
    return new Promise((resolve, reject) => {
        let done = gen(promises.length, resolve);
        promises.forEach((promise, index) => {
            promise.then((value) => {
                done(index, value)
            }, reject)
        })
    })
}

function gen(length, resolve) {
    let count = 0;
    let values = [];
    return function(i, value) {
        values[i] = value;
        if (++count === length) {
            console.log(values);
            resolve(values);
        }
    }
}

/**
 * Promise.race
 * 参数: 接收 promise对象组成的数组作为参数
 * 返回值: 返回一个Promise实例
 * 只要有一个promise对象进入 FulFilled 或者 Rejected 状态的话，就会继续进行后面的处理(取决于哪一个更快)
 */
Promise.race = function(promises) {
    return new Promise((resolve, reject) => {
        promises.forEach((promise, index) => {
           promise.then(resolve, reject);
        });
    });
}

// 用于promise方法链时 捕获前面onFulfilled/onRejected抛出的异常
Promise.prototype.catch = function(onRejected) {
    return this.then(null, onRejected);
}

Promise.resolve = function (value) {
    return new Promise(resolve => {
        resolve(value);
    });
}

Promise.reject = function (reason) {
    return new Promise((resolve, reject) => {
        reject(reason);
    });
}

/**
 * 基于Promise实现Deferred的
 * Deferred和Promise的关系
 * - Deferred 拥有 Promise
 * - Deferred 具备对 Promise的状态进行操作的特权方法（resolve reject）
 *
 *参考jQuery.Deferred
 *url: http://api.jquery.com/category/deferred-object/
 */
Promise.deferred = function() { // 延迟对象
    let defer = {};
    defer.promise = new Promise((resolve, reject) => {
        defer.resolve = resolve;
        defer.reject = reject;
    });
    return defer;
}

/**
 * Promise/A+规范测试
 * npm i -g promises-aplus-tests
 * promises-aplus-tests Promise.js
 */

try {
  module.exports = Promise
} catch (e) {
}
```
